import { chromium } from "@playwright/test";
const B = "https://toolsmith.writingdeveloper.blog";
const b = await chromium.launch();
const m = await b.newPage({ viewport: { width: 390, height: 780 }, deviceScaleFactor: 2 });
await m.goto(B + "/ko"); await m.waitForTimeout(1200);
await m.screenshot({ path: "m-home.png" });
const d = await b.newPage({ viewport: { width: 1000, height: 800 } });
await d.goto(B + "/ko/tools/없는것"); await d.waitForTimeout(1200);
await d.screenshot({ path: "d-404.png" });
await d.goto(B + "/ko"); await d.locator("[data-tool-search]").fill("heic"); await d.waitForTimeout(600);
await d.screenshot({ path: "d-search.png" });
await b.close();
